services:
    auth.provider_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: auth.provider }
    auth.provider.db:
        class: phpbb\auth\provider\db
        arguments:
            - @dbal.conn
            - @config
            - @request
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: auth.provider }
    auth.provider.apache:
        class: phpbb\auth\provider\apache
        arguments:
            - @dbal.conn
            - @config
            - @request
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: auth.provider }
    auth.provider.ldap:
        class: phpbb\auth\provider\ldap
        arguments:
            - @dbal.conn
            - @config
            - @user
        tags:
            - { name: auth.provider }
