services:
    avatar.driver.gravatar:
        class: phpbb_avatar_driver_gravatar
        arguments:
            - @config
            - @request
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        tags:
            - { name: avatar.driver }

    avatar.driver.local:
        class: phpbb_avatar_driver_local
        arguments:
            - @config
            - @request
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        tags:
            - { name: avatar.driver }

    avatar.driver.remote:
        class: phpbb_avatar_driver_remote
        arguments:
            - @config
            - @request
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        tags:
            - { name: avatar.driver }

    avatar.driver.upload:
        class: phpbb_avatar_driver_upload
        arguments:
            - @config
            - @request
            - %core.root_path%
            - .%core.php_ext%
            - @cache.driver
        tags:
            - { name: avatar.driver }
