parameters:
    password_hashing.algorithm: crypto.driver.bcrypt_2y

services:
    crypto.driver.bcrypt:
        class: phpbb_crypto_driver_bcrypt
        arguments:
            - @config
        calls:
            - [set_name, [crypto.driver.bcrypt]]
        tags:
            - { name: crypto.driver }

    crypto.driver.bcrypt_2y:
        class: phpbb_crypto_driver_bcrypt_2y
        arguments:
            - @config
        calls:
            - [set_name, [crypto.driver.bcrypt_2y]]
        tags:
            - { name: crypto.driver }

    crypto.driver.salted_md5:
        class: phpbb_crypto_driver_salted_md5
        arguments:
            - @config
        calls:
            - [set_name, [crypto.driver.salted_md5]]
        tags:
            - { name: crypto.driver }

    crypto.driver.phpass:
        class: phpbb_crypto_driver_phpass
        arguments:
            - @config
        calls:
            - [set_name, [crypto.driver.phpass]]
        tags:
            - { name: crypto.driver }

    crypto.driver_collection:
        class: phpbb_di_service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: crypto.driver }

    crypto.manager:
        class: phpbb_crypto_manager
        arguments:
            - @config
            - @service_container
            - @crypto.driver_collection
            - %password_hashing.algorithm%
