services:
    mimetype.fileinfo_mimetype_guesser:
        class: Symfony\Component\HttpFoundation\File\MimeType\FileinfoMimeTypeGuesser
        tags:
            - { name: mimetype.guessers }

    mimetype.filebinary_mimetype_guesser:
        class: Symfony\Component\HttpFoundation\File\MimeType\FileBinaryMimeTypeGuesser
        tags:
            - { name: mimetype.guessers }

    mimetype.content_guesser:
        class: phpbb\mimetype\content_guesser
        tags:
            - { name: mimetype.guessers }

    mimetype.guesser_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: mimetype.guessers }

    mimetype.guesser:
        class: phpbb\mimetype\guesser
        arguments:
            - @mimetype.guesser_collection
