parameters:
    cache.driver.class: phpbb_cache_driver_file
    dbal.driver.class: dbal_mysqli
    dbal.dbhost:
    dbal.dbuser: root
    dbal.dbpasswd:
    dbal.dbname: phpbb_dev
    dbal.dbport:
    dbal.new_link: false
    tables.config: phpbb_config
    tables.ext: phpbb_ext
