parameters:
    passwords.algorithm: passwords.driver.bcrypt_2y

services:
    passwords.driver.bcrypt:
        class: phpbb_passwords_driver_bcrypt
        arguments:
            - @config
        calls:
            - [set_name, [passwords.driver.bcrypt]]
        tags:
            - { name: passwords.driver }

    passwords.driver.bcrypt_2y:
        class: phpbb_passwords_driver_bcrypt_2y
        arguments:
            - @config
        calls:
            - [set_name, [passwords.driver.bcrypt_2y]]
        tags:
            - { name: passwords.driver }

    passwords.driver.salted_md5:
        class: phpbb_passwords_driver_salted_md5
        arguments:
            - @config
        calls:
            - [set_name, [passwords.driver.salted_md5]]
        tags:
            - { name: passwords.driver }

    passwords.driver.phpass:
        class: phpbb_passwords_driver_phpass
        arguments:
            - @config
        calls:
            - [set_name, [passwords.driver.phpass]]
        tags:
            - { name: passwords.driver }

    passwords.driver_collection:
        class: phpbb_di_service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: passwords.driver }

    passwords.manager:
        class: phpbb_passwords_manager
        arguments:
            - @config
            - @passwords.driver_collection
            - @passwords.helper
            - %passwords.algorithm%

    passwords.helper:
        class: phpbb_passwords_helper
