services:
    profilefields:
        class: \phpbb\profilefields\profilefields
        arguments:
            - @auth
            - @dbal.conn
            - @request
            - @template
            - @user

    profilefields.type.bool:
        class: \phpbb\profilefields\type\type_bool
        arguments:
            - @profilefields
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.date:
        class: \phpbb\profilefields\type\type_date
        arguments:
            - @profilefields
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.dropdown:
        class: \phpbb\profilefields\type\type_dropdown
        arguments:
            - @profilefields
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.int:
        class: \phpbb\profilefields\type\type_int
        arguments:
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.string:
        class: \phpbb\profilefields\type\type_string
        arguments:
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.text:
        class: \phpbb\profilefields\type\type_text
        arguments:
            - @user
        tags:
            - { name: profilefield.type }
