services:
    profilefields:
        class: \phpbb\profilefields\profilefields
        arguments:
            - @auth
            - @dbal.conn
            - @request
            - @template
            - @user
        calls:
            - [set_type_collection, [@profilefields.type_collection]]

    profilefields.lang_helper:
        class: \phpbb\profilefields\lang_helper
        arguments:
            - @dbal.conn

    profilefields.type_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: profilefield.type }

    profilefields.type.bool:
        class: \phpbb\profilefields\type\type_bool
        arguments:
            - @profilefields.lang_helper
            - @request
            - @template
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.date:
        class: \phpbb\profilefields\type\type_date
        arguments:
            - @profilefields
            - @request
            - @template
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.dropdown:
        class: \phpbb\profilefields\type\type_dropdown
        arguments:
            - @profilefields.lang_helper
            - @request
            - @template
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.int:
        class: \phpbb\profilefields\type\type_int
        arguments:
            - @request
            - @template
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.string:
        class: \phpbb\profilefields\type\type_string
        arguments:
            - @request
            - @template
            - @user
        tags:
            - { name: profilefield.type }

    profilefields.type.text:
        class: \phpbb\profilefields\type\type_text
        arguments:
            - @request
            - @template
            - @user
        tags:
            - { name: profilefield.type }
