services:
    installer.install_data.add_bots:
        class: phpbb\install\module\install_data\task\add_bots
        arguments:
            - @installer.helper.config
            - @installer.helper.iohandler
            - @installer.helper.container_factory
            - @language
            - %core.root_path%
            - %core.php_ext%

    installer.install_data.add_languages:
        class: phpbb\install\module\install_data\task\add_languages
        arguments:
            - @installer.helper.iohandler
            - @installer.helper.container_factory
            - @language.helper.language_file

    installer.install_data.add_modules:
        class: phpbb\install\module\install_data\task\add_modules
        arguments:
            - @installer.helper.iohandler
            - @installer.helper.container_factory

    installer.module.data_install:
        class: phpbb\install\module\install_data\module
        parent: installer.module_base
        arguments:
            - ["installer.install_data.add_languages", "installer.install_data.add_bots", "installer.install_data.add_modules"]
