services:
    installer.install_finish.populate_migrations:
        class: phpbb\install\module\install_finish\task\populate_migrations
        arguments:
            - @installer.helper.container_factory

    installer.install_finish.notify_user:
        class: phpbb\install\module\install_finish\task\notify_user
        arguments:
            - @installer.helper.container_factory
            - @installer.helper.config
            - @installer.helper.iohandler
            - %core.root_path%
            - %core.php_ext%

    installer.module.finish_install:
        class: phpbb\install\module\install_filesystem\module
        parent: installer.module_base
        arguments:
            - ["installer.install_finish.populate_migrations", "installer.install_finish.notify_user"]
