imports:
    - { resource: services_install_controller.yml }
    - { resource: services_install_data.yml }
    - { resource: services_install_database.yml }
    - { resource: services_install_filesystem.yml }
    - { resource: services_install_finish.yml }
    - { resource: services_install_navigation.yml }
    - { resource: services_install_obtain_data.yml }
    - { resource: services_install_requirements.yml }

services:
# -------- Installer helpers ------------------------
    installer.helper.config:
        class: phpbb\install\helper\config
        arguments:
            - @filesystem
            - @php_ini
            - %core.root_path%

    installer.helper.database:
        class: phpbb\install\helper\database
        arguments:
            - @filesystem
            - %core.root_path%

    installer.helper.iohandler_factory:
        class: phpbb\install\helper\iohandler\factory
        arguments:
            - @service_container

    installer.helper.iohandler_abstract:
        abstract: true
        calls:
            - [set_language, ["@language"]]

    installer.helper.iohandler_ajax:
        class: phpbb\install\helper\iohandler\ajax_iohandler
        parent: installer.helper.iohandler_abstract
        arguments:
            - @request
            - @template

    installer.helper.iohandler:
        class: phpbb\install\helper\iohandler\iohandler_interface
        factory: ["@installer.helper.iohandler_factory", get]

    installer.helper.container_factory:
        class: phpbb\install\helper\container_factory
        arguments:
            - @request
            - %core.root_path%
            - %core.php_ext%

# -------- Installer --------------------------------
    installer.module_base:
        abstract: true
        calls:
            - [setup, [@service_container, @installer.helper.config, @installer.helper.iohandler]]

    installer.installer.abstract:
        class: phpbb\install\installer
        abstract: true
        arguments:
            - @installer.helper.config
            - @service_container

    installer.installer.install:
        parent: installer.installer.abstract
        calls:
            - [set_modules, [["installer.module.requirements_install", "installer.module.obtain_data_install", "installer.module.filesystem_install", "installer.module.database_install", "installer.module.data_install", "installer.module.finish_install"]]]
